version: 0.2

phases:

  pre_build:
    commands:
      - pip3 install -r requirements.txt

  build:
    commands:
      - pytest

  post_build:
    commands:
      - pwd
      - ls -rtla
      - mkdir build
      - cp requirements.txt build/
      - cp src/*.py build/
      - ls -rtla
      - df -h

artifacts:

  files:
    - '**/*'
  base-directory: build
